---
# tasks file for productivity

# fix varmilo keyboard fn key
# https://help.ubuntu.com/community/AppleKeyboard#Change_Function_Key_behavior
- name: Fix varmilo/apple fn key default
  copy:
    src: "{{ role_path }}/files/hid_apple.conf"
    dest: /etc/modprobe.d/hid_apple.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - update initramfs

- name: Import Google Chrome repo gpg key
  apt_key:
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present

- name: Add Google Chrome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: 'google-chrome'

- name: Import syncthing repo gpg key
  apt_key:
    id: 37C84554E7E0A261E4F76E1ED26E6ED000654A3E
    url: 'https://syncthing.net/release-key.txt'
    state: present

- name: Add syncthing release repo
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing release
    state: present
    filename: 'syncthing'

- name: Import Typora repo gpg key
  apt_key:
    id: BA300B7755AFCFAE
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add Typora repo
  apt_repository:
    repo: deb https://typora.io/linux ./
    state: present
    filename: 'typora'

- name: Import Spotify repo gpg key
  apt_key:
    id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
    url: 'https://download.spotify.com/debian/pubkey.gpg'
    state: present

- name: Add Spotify repo
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: 'spotify'

- name: Install productivity packages
  package: name={{ item }} state=latest
  with_items:
  - gnome-tweak-tool
  - weechat
  - gufw
  - zsh-syntax-highlighting
  - autojump
  - vlc
  - yadm
  - google-chrome-stable
  - syncthing
  - typora
  - spotify-client
  - magic-wormhole
  - redshift-gtk
