---
# Variables listed here are applicable to the printservers host group
base_packages_supplemental:
  debian-keyring: latest
  debian-archive-keyring: latest

ufw_state: enabled

ufw_rules_named:
  - name: Bonjour
  - name: IPP
  - name: OpenSSH

additional_packages_supplemental:
  openssh-server: latest
