---
# tasks file for golang
- name: Ensure /usr/local/src/go
  file:
    path: /usr/local/src/go
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add go bin to path sh
  copy:
    src: "{{ role_path }}/files/go.sh"
    dest: /etc/profile.d/go.sh
    owner: root
    group: root
    mode: 0644

- name: Add go bin to path zsh
  copy:
    src: "{{ role_path }}/files/zshenv"
    dest: /etc/zsh/zshenv
    owner: root
    group: root
    mode: 0644

- name: Download golang
  get_url:
    url: https://dl.google.com/go/go1.11.4.linux-armv6l.tar.gz
    dest: /usr/local/src/go/go.linux-armv6l.tar.gz
    checksum: sha256:9f7a71d27fef69f654a93e265560c8d9db1a2ca3f1dcdbe5288c46facfde5821

- name: Unarchive golang src
  unarchive:
    src: /usr/local/src/go/go.linux-armv6l.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
    owner: root
    group: root
