---
# tasks file for security

- name: Install yubico repo
  apt_repository:
    repo: 'ppa:yubico/stable'

- name: Install security packages
  package: name={{ item }} state=latest
  with_items:
    - pcscd
    - pcsc-tools
    - scdaemon
    - gnupg2
    - hopenpgp-tools
    - yubioath-desktop
    - yubikey-personalization-gui
    - yubikey-manager
