---
# tasks file for security

- name: Install yubico repo
  apt_repository:
    repo: 'ppa:yubico/stable'

- name: Install keybase from https://keybase.io
  apt:
    deb: 'https://prerelease.keybase.io/keybase_amd64.deb'

- name: Add tor repo gpg key
  apt_key:
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    keyserver: keys.gnupg.net

- name: Install tor repo
  apt_repository:
    repo: deb https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main
    state: present
    filename: tor

- name: Install torbrowser-launcher ppa
  apt_repository:
    repo: 'ppa:micahflee/ppa'

- name: Install security packages
  package: name={{ item }} state=latest
  with_items:
    - pcscd
    - pcsc-tools
    - scdaemon
    - gnupg2
    - hopenpgp-tools
    - pass
    - yubioath-desktop
    - yubikey-personalization-gui
    - yubikey-manager-qt
    - tor
    - torbrowser-launcher
    - deb.torproject.org-keyring
    - network-manager-openvpn-gnome
