---
# tasks file for security

- name: Install yubico repo
  apt_repository:
    repo: 'ppa:yubico/stable'

- name: Install keybase from https://keybase.io
  apt:
    deb: 'https://prerelease.keybase.io/keybase_amd64.deb'

- name: Add tor repo gpg key
  apt_key:
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    keyserver: keys.gnupg.net

- name: Install tor repo
  apt_repository:
    repo: deb http://deb.torproject.org/torproject.org xenial main
    state: present
    filename: tor

- name: Install tor repo
  apt_repository:
    repo: deb-src http://deb.torproject.org/torproject.org xenial main
    state: present
    filename: tor

- name: Ensure /etc/lightdm/lightdm.conf.d dir exists
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup lightdm settings to disable guest sessions
  copy:
    src: "{{ role_path }}/files/lightdm_50-no-guest.conf"
    dest: /etc/lightdm/lightdm.conf.d/50-no-guest.conf
    owner: root
    group: root
    mode: 0644

- name: Install the standby lockscript
  copy:
    src: "{{ role_path }}/files/systemd_sleep-locker.service"
    dest: /etc/systemd/system/sleep-locker.service
    owner: root
    group: root
    mode: 0644

- name: Enable standby lockscript with systemd
  systemd:
    name: sleep-locker
    enabled: yes

- name: Install security packages
  package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - pcscd
    - pcsc-tools
    - scdaemon
    - gnupg2
    - pass
    - yubioath-desktop
    - yubikey-personalization-gui
    - yubikey-neo-manager
    - tor
    - torbrowser-launcher
    - deb.torproject.org-keyring
    - network-manager-openvpn-gnome
