---
# tasks file for windowmanager-i3

- name: Import i3 repo gpg key
  apt_key:
    id: BFD90F4DAAEFA72B67BBAF48E3CA1A89941C42E6
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add i3 repo
  apt_repository:
    repo: deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe
    state: present
    filename: 'i3wm'

- name: Install i3 keyring sur5r
  apt:
    name: sur5r-keyring
    update_cache: true

- name: Configure terminal tty
  vars:
    console_font_size: "10x20"
  template:
    src: "{{ role_path }}/templates/console-setup.js"
    dest: /etc/default/console-setup
    owner: root
    group: root
    mode: 0644

- name: Install i3 packages and utilities
  package: name={{ item }} state=latest
  with_items:
  - xfce4-settings
  - xfce4-volumed
  - volumeicon-alsa
  - xfce4-power-manager
  - blueman
  - i3
  - pulseaudio-utils
  - xbacklight
  - fonts-font-awesome
  - xfonts-terminus
  - fonts-dejavu-core
  - feh
  - thunar
  - scrot
  - light-locker
  - light-locker-settings
