---
# tasks file for roles/smbserver
- name: Install samba server packages
  package: name={{ item }} state=latest
  with_items:
    - samba

- name: Stop and disable netbios service
  systemd:
    name: nmbd
    enabled: no
    state: stopped

- name: Start and enable smbd service
  systemd:
    name: smbd
    daemon_reload: yes
    enabled: yes
    state: started

- name: Create smb conf.d include directory
  file:
    name: /etc/samba/smb.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Template smb.conf
  template:
    src: "{{ role_path }}/templates/smb.conf.j2"
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    validate: /bin/testparm -s %s
    backup: yes
  notify: restart smbd

- name: Template shares.conf
  template:
    src: "{{ role_path }}/templates/shares.conf.j2"
    dest: /etc/samba/smb.conf.d/shares.conf
    owner: root
    group: root
    mode: '0644'
    validate: /bin/testparm -s %s
    backup: yes
  notify: restart smbd
