---
# tasks file for homeconfig

- name: Checkout oh-my-zsh
  become: yes
  become_user: derek
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: /home/derek/.oh-my-zsh
    update: no
    depth: 1
    umask: '0022'

- name: Checkout zsh-syntax-highlighting
  become: yes
  become_user: derek
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: /home/derek/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: no
    depth: 1
    umask: '0022'

- name: Checkout zsh-autosuggestions
  become: yes
  become_user: derek
  git:
    repo: 'git://github.com/zsh-users/zsh-autosuggestions'
    dest: /home/derek/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: no
    depth: 1
    umask: '0022'

- name: Create ~/bin dir
  file:
    path: /home/derek/bin
    state: directory
    owner: derek
    group: derek
    mode: 0755

- name: Create yadm config dir
  file:
    path: /home/derek/.config/yadm
    state: directory
    owner: derek
    group: derek
    mode: 0700

- name: Copy yadm config to /home/derek/.config/yadm/config
  copy:
    src: "{{ role_path }}/files/yadm_config"
    dest: /home/derek/.config/yadm/config
    owner: derek
    group: derek
    mode: 0644

- name: Create Development dir
  file:
    path: /home/derek/Development
    state: directory
    owner: derek
    group: derek
    mode: 0755
