---
# tasks file for printserver

- name: Install print server packages
  package: name={{ item }} state=latest
  with_items:
    - avahi-daemon
    - cups

- name: Setup cupsd settings
  copy:
    src: "{{ role_path }}/files/cupsd.conf"
    dest: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/cupsd -t -c %s
  notify:
    - restart cups

- name: Add derek to lpadmin group
  user:
    name: derek
    groups: lpadmin
    append: yes

- name: Enable cups service
  systemd:
    name: cups
    daemon_reload: yes
    enabled: yes
    state: started
