---
# tasks file for docker-services

- name: Install pip to setup managment utils
  package: name={{ item }} state=latest
  with_items:
    - python-pip

- name: Install pip utils to manage docker
  pip: name={{ item }} state=present
  with_items:
    - docker
    - docker-compose

- name: Cache docker-gitserver for docker-compose
  git:
    repo: https://github.com/derektamsen/docker-gitserver.git
    dest: /apps/containers/docker-gitserver
    depth: 1

- name: Use compose to start gitserver
  register: output
  docker_service:
    project_src: /apps/containers/docker-gitserver
    pull: yes
    build: no

- name: Docker compose output
  debug:
    var: output

- name: Ensure containers are running
  assert:
    that:
      - "gitserver.dockergitserver_gitserver_1.state.running"
