---
# tasks file for development

- name: Install virtualbox repo gpg key
  apt_key:
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present

- name: Add virtualbox repo
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    state: present
    filename: virtualbox

- name: Install docker repo gpg key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: 'hkp://ha.pool.sks-keyservers.net:80'

- name: Add docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present
    filename: docker

- name: Install atom from https://atom.io
  apt:
    deb: 'https://atom.io/download/deb'

- name: Copy tldr bash script to /usr/local/bin
  copy:
    src: "{{ role_path }}/files/tldr"
    dest: /usr/local/bin/tldr
    owner: root
    group: root
    mode: 0755

- name: Install Zeal PPA
  apt_repository:
    repo: 'ppa:zeal-developers/ppa'

- name: Download and untar Postman
  unarchive:
    src: "https://dl.pstmn.io/download/latest/linux64"
    dest: /opt
    owner: root
    group: root
    remote_src: yes
    creates: /opt/Postman/Postman

- name: Link Postman /usr/local/bin/postman
  file:
    src: /opt/Postman/Postman
    dest: /usr/local/bin/postman
    state: link

- name: Install Vagrant from https://vagrantup.com
  apt:
    deb: 'https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb'

- name: Install development packages
  package: name={{ item }} state=latest
  with_items:
    - vim
    - exfat-fuse
    - exfat-utils
    - build-essential
    - htop
    - iotop
    - iftop
    - sshfs
    - zeal
    - dkms
    - virtualbox-5.1
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
    - docker-engine
    - docker-compose
