---
# tasks file for development

- name: Install atom from https://atom.io
  apt:
    deb: 'https://atom.io/download/deb'

- name: Copy tldr bash script to /usr/local/bin
  copy:
    src: "{{ role_path }}/files/tldr"
    dest: /usr/local/bin/tldr
    owner: root
    group: root
    mode: 0755

- name: Install Zeal PPA
  apt_repository:
    repo: 'ppa:zeal-developers/ppa'
    codename: 'yakkety'

- name: Download and untar Postman
  unarchive:
    src: "https://dl.pstmn.io/download/latest/linux64"
    dest: /opt
    owner: root
    group: root
    remote_src: yes
    creates: /opt/Postman/Postman

- name: Link Postman /usr/local/bin/postman
  file:
    src: /opt/Postman/Postman
    dest: /usr/local/bin/postman
    state: link

- name: Install development packages
  package: name={{ item }} state=latest
  with_items:
    - vim
    - vim-gnome
    - exfat-fuse
    - exfat-utils
    - build-essential
    - sshfs
    - zeal
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
    - gparted
    - exuberant-ctags
    - tig
    - ipcalc
    - whois
