---
# tasks file for development

- name: Import visualstudio code repo gpg key
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Add visualstudio code repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: 'vscode'

- name: Import github gh repo gpg key
  apt_key:
    id: C99B11DEB97541F0
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add github gh repo
  apt_repository:
    repo: deb https://cli.github.com/packages focal main
    state: present
    filename: 'gh'

- name: Download and untar Postman
  unarchive:
    src: "https://dl.pstmn.io/download/latest/linux64"
    dest: /opt
    owner: root
    group: root
    remote_src: yes
    creates: /opt/Postman/Postman

- name: Link Postman /usr/local/bin/postman
  file:
    src: /opt/Postman/Postman
    dest: /usr/local/bin/postman
    state: link

- name: Install development packages
  package: name={{ item }} state=latest
  with_items:
    - vim
    - build-essential
    - tig
    - ipcalc
    - whois
    - code
    - gh
