---
# tasks file for development

- name: Install atom from https://atom.io
  apt:
    deb: 'https://atom.io/download/deb'

- name: Import visualstudio code repo gpg key
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Add visualstudio code repo
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: 'vscode'

- name: Copy tldr bash script to /usr/local/bin
  copy:
    src: "{{ role_path }}/files/tldr"
    dest: /usr/local/bin/tldr
    owner: root
    group: root
    mode: 0755

- name: Install Zeal PPA
  apt_repository:
    repo: 'ppa:zeal-developers/ppa'

- name: Download and untar Postman
  unarchive:
    src: "https://dl.pstmn.io/download/latest/linux64"
    dest: /opt
    owner: root
    group: root
    remote_src: yes
    creates: /opt/Postman/Postman

- name: Link Postman /usr/local/bin/postman
  file:
    src: /opt/Postman/Postman
    dest: /usr/local/bin/postman
    state: link

- name: Ensure /usr/local/src/hub
  file:
    path: /usr/local/src/hub
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download hub
  get_url:
    url: https://github.com/github/hub/releases/download/v2.11.2/hub-linux-amd64-2.11.2.tgz
    dest: /usr/local/src/hub/hub-linux-amd64.tgz
    checksum: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

- name: Unarchive hub src
  unarchive:
    src: /usr/local/src/hub/hub-linux-amd64.tgz
    dest: /opt/hub
    extra_opts: [--strip-components=1]
    remote_src: yes
    creates: /opt/hub/bin/hub
    owner: root
    group: root

- name: Link hub /usr/local/bin/hub
  file:
    src: /opt/hub/bin/hub
    dest: /usr/local/bin/hub
    state: link

- name: Install development packages
  package: name={{ item }} state=latest
  with_items:
    - vim
    - vim-gnome
    - exfat-fuse
    - exfat-utils
    - build-essential
    - sshfs
    - zeal
    - gparted
    - exuberant-ctags
    - tig
    - ipcalc
    - whois
    - code
