---
# Variables listed here are applicable to the nas host group
ufw_state: enabled

ufw_rules_named:
  - name: OpenSSH
  - name: Samba

user_groups_supplemental:
  media_users: {}
  backup_users: {}

users_supplemental:
  derek:
    groups: '{{ users.derek.groups }}, media_users, backup_users'

zfs:
  datasets:
    - name: tank/docker-volumes
      state: present
    - name: tank/home
      state: present
    - name: tank/media
      state: present
    - name: tank/backups
      state: present

smbserver:
  shares:
    homes:
      comment: Home Directories
      browseable: 'no'
      vfs_objects: recycle
      recycle_repository: .recycle
      recycle_keeptree: 'yes'
      recycle_versions: 'yes'
      read_only: 'no'
      valid_users: '%S'
      path: '/tank/home/%S'
    media:
      comment: Music, Movies, and TV
      path: /tank/media
      valid_users: '@media_users'
      public: 'no'
      writable: 'yes'
      vfs_objects: recycle
      recycle_repository: .recycle
      recycle_keeptree: 'yes'
      recycle_versions: 'yes'
    backups:
      comment: System Backups
      path: /tank/backups
      valid_users: '@backup_users'
      public: 'no'
      writable: 'yes'
      vfs_objects: recycle
      recycle_repository: .recycle
      recycle_keeptree: 'yes'
      recycle_versions: 'yes'
