---
# tasks file for nomad

- name: Create /opt/nomad
  file:
    path: /opt/nomad
    state: directory
    owner: root
    group: root
    mode: 0755
  register: nomad_dir

- name: Create /opt/nomad/src
  file:
    path: '{{ nomad_dir.path }}/src'
    state: directory
    owner: root
    group: root
    mode: 0755
  register: nomad_src_dir

- name: Create /etc/nomad.d
  file:
    path: /etc/nomad.d
    state: directory
    owner: root
    group: root
    mode: 0700
  register: nomad_etc_dir

- name: Download nomad
  get_url:
    url: '{{ nomad.url }}'
    dest: '{{ nomad_src_dir.path }}/nomad.zip'
    checksum: '{{ nomad.checksum }}'
  register: nomad_zip

- name: Install nomad
  unarchive:
    src: '{{ nomad_zip.dest }}'
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  register: nomad_archive

- name: Add nomad unit file
  template:
    src: '{{ role_path }}/templates/nomad.service.j2'
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: Configure nomad common
  template:
    src: '{{ role_path }}/templates/nomad.hcl.j2'
    dest: '{{ nomad_etc_dir.path }}/nomad.hcl'
    owner: root
    group: root
    mode: 0600
  notify:
    - restart nomad

- name: Configure nomad server
  template:
    src: '{{ role_path }}/templates/server.hcl.j2'
    dest: '{{ nomad_etc_dir.path }}/server.hcl'
    owner: root
    group: root
    mode: 0600
  notify:
    - restart nomad

- name: Configure nomad client
  template:
    src: '{{ role_path }}/templates/client.hcl.j2'
    dest: '{{ nomad_etc_dir.path }}/client.hcl'
    owner: root
    group: root
    mode: 0600
  notify:
    - restart nomad

- name: Ensure nomad is enabled and running
  systemd:
    name: nomad
    enabled: yes
    state: started
