---
# Variables listed here are applicable to the desktops host group
additional_repos_supplemental:
  docker:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

additional_repo_keys_supplemental:
  docker:
    key_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    state: present

additional_packages_supplemental:
  docker-ce: "latest"
  docker-ce-cli: "latest"
  "containerd.io": "latest"
