---
# tasks file for laptophw

- name: Install packages for mobile systems
  package: name={{ item }} state=latest
  with_items:
    - tlp
    - powertop
    - xserver-xorg-input-libinput

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes

- name: Ensure /etc/X11/xorg.conf.d dir exists
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup xorg settings for intel graphics
  copy:
    src: "{{ role_path }}/files/xorg_10-intel.conf"
    dest: /etc/X11/xorg.conf.d/10-intel.conf
    owner: root
    group: root
    mode: 0644
