---
# tasks file for laptophw

- name: Install packages for mobile systems
  package: name={{ item }} state=latest
  with_items:
    - tlp
    - powertop

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes
