---
# tasks file for laptophw

- name: Install packages for mobile systems
  package: name={{ item }} state=latest
  with_items:
    - tlp
    - powertop

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes

- name: Ensure /etc/X11/xorg.conf.d dir exists
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup xorg settings for synaptics touchpads
  copy:
    src: "{{ role_path }}/files/xorg_50-synaptics.conf"
    dest: /etc/X11/xorg.conf.d/50-synaptics.conf
    owner: root
    group: root
    mode: 0644

- name: Setup xorg settings for intel graphics
  copy:
    src: "{{ role_path }}/files/xorg_10-intel.conf"
    dest: /etc/X11/xorg.conf.d/10-intel.conf
    owner: root
    group: root
    mode: 0644

- name: Install the standby lockscript
  copy:
    src: "{{ role_path }}/files/systemd_sleep-locker.service"
    dest: /etc/systemd/system/sleep-locker.service
    owner: root
    group: root
    mode: 0644

- name: Enable standby lockscript with systemd
  systemd:
    name: sleep-locker
    enabled: yes
