---
# tasks file for laptophw

- name: Install packages for mobile systems
  package: name={{ item }} state=latest
  with_items:
    - tlp
    - powertop
    - xserver-xorg-input-libinput
    - tpm2-tools
    - tss2

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes

- name: Ensure /etc/X11/xorg.conf.d dir exists
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup xorg settings for intel graphics
  copy:
    src: "{{ role_path }}/files/xorg_10-intel.conf"
    dest: /etc/X11/xorg.conf.d/10-intel.conf
    owner: root
    group: root
    mode: 0644

- name: Template powertop unit file
  template:
    src: "{{ role_path }}/templates/powertop.service.j2"
    dest: /etc/systemd/system/powertop.service
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: reload powertop

- name: Ensure powertop is enabled and running
  systemd:
    name: powertop
    enabled: yes
    state: started

- name: Ensure /etc/udev/rules.d/80-tpm-2.rules exists
  copy:
    src: "{{ role_path }}/files/udev_80-tpm-2.rules"
    dest: /etc/udev/rules.d/80-tpm-2.rules
    owner: root
    group: root
    mode: 0644

- name: Checkout tpm2-luks
  git:
    repo: 'https://github.com/rqou/tpm2-luks.git'
    dest: /opt/tpmdisk
    update: no
    depth: 1
    umask: '0022'

# - name: Ensure zzz-tpmdisk in /usr/share/initramfs-tools/hooks/
#   copy:
#     src: /opt/tpmdisk/zzz-tpmdisk
#     dest: /usr/share/initramfs-tools/hooks/zzz-tpmdisk
#     owner: root
#     group: root
#     mode: 0755
