---
# tasks file for virtualization

- name: Install libvirt packages
  package: name={{ item }} state=latest
  with_items:
    - qemu-kvm
    - qemu-utils
    - libvirt-bin
    - libvirt-dev
    - ubuntu-vm-builder
    - bridge-utils
    - virt-manager
    - ruby-dev

- name: Install Vagrant from https://vagrantup.com
  apt:
    deb: 'https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb'

- name: Install Vagrant mutate plugin
  command: vagrant plugin install vagrant-mutate
