---
# tasks file for virtualization

- name: Install virtualbox packages
  package: name={{ item }} state=latest
  with_items:
    - virtualbox

- name: Install Vagrant from https://vagrantup.com
  apt:
    deb: 'https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb'
