---
# tasks file for docker

- name: Install docker-ce repo gpg key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: 'https://download.docker.com/linux/ubuntu/gpg'

- name: Add docker-ce repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ docker.distro }} stable
    state: present
    filename: docker

- name: Install docker-compose from github
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.5/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: Install docker packages
  package: name={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
