---
# tasks file for docker

- name: Install docker repo gpg key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: 'hkp://ha.pool.sks-keyservers.net:80'

- name: Add docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ docker.distro }} main
    state: present
    filename: docker

- name: Install docker-compose from github
  get_url:
    url: https://github.com/docker/compose/releases/download/1.17.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: Install development packages
  package: name={{ item }} state=latest
  with_items:
    - docker-engine
