---
# tasks file for base

- name: Install base packages
  package:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
  with_dict: "{{ base_packages | combine(base_packages_supplemental, recursive=True)}}"

- name: Configure unattended-upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: 'true'
    vtype: boolean

- name: Set ntp time servers
  template:
    src: "{{ role_path }}/templates/timesyncd.conf.j2"
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart systemd-timesyncd

- name: Enable UFW firewall
  when: ufw_state is defined
  ufw:
    state: "{{ ufw_state }}"

- name: Enable UFW firewall rules only if they are specified
  when: ufw_rules_allow is defined
  ufw:
    rule: allow
    name: "{{ item.name }}"
  with_items: "{{ ufw_rules_allow }}"

- name: "Add group {{ item.key }}"
  group:
    name: "{{ item.key }}"
  with_dict: "{{ user_groups | combine(user_groups_supplemental, recursive=True) }}"

- name: "Add account for {{ item.key }}"
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.comment }}"
    shell: "{{ item.value.shell }}"
    groups: "{{ item.value.groups }}"
    append: "{{ item.value.append }}"
  with_dict: "{{ users | combine(users_supplemental, recursive=True) }}"

- name: "Set authorized keys for {{ item.key }}"
  authorized_key:
    user: "{{ item.key }}"
    state: "{{ item.value.state }}"
    key: "{{ item.value.key }}"
  with_dict: "{{ ssh_authorized_keys | combine(ssh_authorized_keys_supplemental, recursive=True) }}"

- name: Ensure lm-sensors is enabled and running
  systemd:
    name: lm-sensors
    enabled: yes
    state: started

- name: Install {{ item.key }} repo gpg key
  apt_key:
    id: "{{ item.value.key_id }}"
    keyserver: "{{ item.value.keyserver }}"
  with_dict: "{{ additional_repo_keys | combine(additional_repo_keys_supplemental, recursive=True) }}"

- name: Add {{ item.key }} repo
  apt_repository:
    repo: "{{ item.value.repo }}"
    state: "{{ item.value.state }}"
    filename: "{{ item.key }}"
  with_dict: "{{ additional_repos | combine(additional_repos_supplemental, recursive=True) }}"

- name: Add additional packages
  package:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
  with_dict: "{{ additional_packages | combine(additional_packages_supplemental, recursive=True) }}"
