---
# tasks file for base

- name: Install base packages
  package: name={{ item }} state=latest
  with_items:
    - unattended-upgrades
    - apt-transport-https
    - ca-certificates
    - htop
    - iotop
    - iftop
    - tmux

- name: Configure unattended-upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: true
    vtype: boolean

- name: Set ntp time servers
  template:
    src: "{{ role_path }}/templates/timesyncd.conf.j2"
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart systemd-timesyncd
