---
# tasks file for base

- name: Install base packages
  package: name={{ item }} state=latest
  with_items:
    - unattended-upgrades

- name: Configure unattended-upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: true
    vtype: boolean
