---
# tasks file for base

- name: Install base packages
  package:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
  with_dict: "{{ base_packages | combine(base_packages_supplemental, recursive=true) }}"

- name: Configure unattended-upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: 'true'
    vtype: boolean

- name: Set ntp time servers
  template:
    src: "{{ role_path }}/templates/timesyncd.conf.j2"
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart systemd-timesyncd

- name: Enable UFW firewall
  when: ufw_state is defined
  ufw:
    state: "{{ ufw_state }}"

- name: Enable named UFW firewall rules
  when: ufw_rules_named is defined
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    name: "{{ item.name }}"
  with_items: "{{ ufw_rules_named }}"

- name: Enable port UFW firewall rules
  when: ufw_rules_ports is defined
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
  with_items: "{{ ufw_rules_ports }}"

- name: "Add group {{ item.key }}"
  group:
    name: "{{ item.key }}"
  with_dict: "{{ user_groups | combine(user_groups_supplemental, recursive=true) }}"

- name: "Add account for {{ item.key }}"
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.comment }}"
    shell: "{{ item.value.shell }}"
    groups: "{{ item.value.groups }}"
    append: "{{ item.value.append }}"
  with_dict: "{{ users | combine(users_supplemental, recursive=true) }}"

- name: "Set authorized keys for {{ item.key }}"
  authorized_key:
    user: "{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"
    key: "{{ item.value.key }}"
    exclusive: "{{ item.value.exclusive | default(true) }}"
  with_dict: "{{ ssh_authorized_keys | combine(ssh_authorized_keys_supplemental, recursive=true) }}"

- name: Ensure lm-sensors is enabled and running
  systemd:
    name: lm-sensors
    enabled: yes
    state: started

- name: Install {{ item.key }} repo gpg key
  apt_key:
    id: "{{ item.value.key_id }}"
    keyserver: "{{ item.value.keyserver }}"
    state: "{{ item.value.state | default('present') }}"
  with_dict: "{{ additional_repo_keys | combine(additional_repo_keys_supplemental, recursive=true) }}"

- name: Add {{ item.key }} repo
  apt_repository:
    repo: "{{ item.value.repo }}"
    state: "{{ item.value.state | default('present') }}"
    filename: "{{ item.key }}"
  with_dict: "{{ additional_repos | combine(additional_repos_supplemental, recursive=true) }}"

- name: Add additional packages
  package:
    name: "{{ item.key }}"
    state: "{{ item.value | default('latest') }}"
  with_dict: "{{ additional_packages | combine(additional_packages_supplemental, recursive=true) }}"

- name: Add additional apt packages
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('latest') }}"
    default_release: "{{ item.value.release }}"
  with_dict: "{{ additional_packages_apt | combine(additional_packages_apt_supplemental, recursive=true) }}"

- name: Add additional snaps
  snap:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('present')}}"
    channel: "{{ item.value.channel | default('stable') }}"
    classic: "{{ item.value.classic | default(false) }}"
  with_dict: "{{ additional_snaps | combine(additional_snaps_supplemental, recursive=true) }}"
